GET http://localhost:4000/decks

###

POST http://localhost:4000/decks
content-type: application/json

{
	"name": "Deck 1",
	"cards": [
		{
			"_id": "me01-096",
			"variants": {
				"normal": 1
			}
		},
		{
			"_id": "me01-112",
			"variants": {
				"normal": 1
			}
		}
	]
}
